config/routes.rb
Gallery::Application.routes.draw do

  resources :photos do
    collection do
      match 'upload'
      get 'by-tag/:tag' => 'photos#index', :as => :tagged
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  process_in_background :image

  acts_as_taggable

  def shot_on
    self.shot_at.to_date
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    if params[:tag]
      @photos = Photo.tagged_with(params[:tag])
    else
      @photos = Photo.all
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
    @attr_name = params[:attr]
    if request.xhr?
      render :partial => 'form'
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if params[:photo]
      if @photo.update_attributes(params[:photo])
        if request.xhr?
          render :partial => 'editable_attr', :locals => { :attr_name => params[:photo].keys.first, :attr_value => params[:photo].values.first }
        else
          redirect_to(@photo)
        end
      else
        if request.xhr?
          render :partial => 'form'
        else
          render 'edit'
        end
      end
    end
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new
    if params[:photo]
      if @photo.update_attributes(params[:photo])
        redirect_to(@photo)
      else
        render :action => 'new'
      end
    end
  end

  def upload
    if request.post?
      params['images'].each do |image|
        photo = Photo.new(:image => image)
        photo.title = photo.image.identifier
        photo.shot_at = DateTime.now
        photo.save
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Gallery
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .content= yield
    .sidebar
      %ul
        %li= link_to 'Library', photos_path
        %li= link_to 'Upload', upload_photos_path
        %li
          Tags
          %ul.tags_list
            - Tag.all.each do |tag|
              %li.tag= link_to tag.name, tagged_photos_path(:tag => tag.name)

app/views/photos/_editable_attr.html.haml
%div{ :class => ['editable_attr', attr_name], :data => { :attr_name => attr_name } }
  = link_to(attr_value, '#')

app/views/photos/_form.html.haml
= form_for @photo do |form|
  = form.text_field @attr_name # TODO: whitelist attributes!

app/views/photos/edit.html.haml
= render :partial => 'form'

app/views/photos/index.html.haml
%ul.thumbs_list
  - @photos.each do |photo|
    %li.thumb
      .image= link_to(image_tag(photo.image_processing ? 'default-thumbnail.png' : photo.image.url(:thumb), :size => '100x100'), photo_url(:id => photo.id))
      .title{ :title => photo.title }= photo.title
      .tags{ :title => photo.tag_list }= photo.tag_list

app/views/photos/show.html.haml
.photo
  .image= image_tag(@photo.image.url, 'data-image-width' => @photo.image_width, 'data-image-height' => @photo.image_height)
  = render :partial => 'editable_attr', :locals => { :attr_name => 'title', :attr_value => @photo.title }
  = render :partial => 'editable_attr', :locals => { :attr_name => 'tag_list', :attr_value => @photo.tag_list.empty? ? 'no tags' : @photo.tag_list }

:javascript
  $(function() {
    $(window).bind('load resize', function() {
      $('.photo .image img').each(function() {
        var imageElement = $(this);
        var imageContainer = $(this).parent('.image');
        if (imageElement.data('imageWidth') / imageElement.data('imageHeight') >= imageContainer.innerWidth() / imageContainer.innerHeight()) {
          imageElement.css('width', imageContainer.innerWidth() + 'px');
        } else {
          imageElement.css('height', imageContainer.innerHeight() + 'px');
        }
      });
    });

    $('.photo').on('click', '.editable_attr a', function() {
      var container = $(this).parent();
      var attr = container.data('attr_name');
      // FIXME: fix attr sending
      container.load('#{edit_photo_path(@photo)}?attr=' + encodeURIComponent(attr), function() {
        container.find('form').submit(function() {
          // FIXME: fix attr sending
          $.post($(this).attr('action'), $(this).serialize() + '&attr=' + encodeURIComponent(attr), function(data) {
            container.replaceWith(data);
          });
          return false;
        });
      });
      return false;
    });
  });

app/views/photos/upload.html.haml
= form_tag({}, { :class => 'upload_form', :multipart => true }) do
  %p
    = file_field_tag 'images[]', :multiple => true, :class => 'upload_images'
    = submit_tag 'Upload'
  %p
    = check_box_tag 'generate_thumbnails', 1, true, :id => 'generate_thumbnails'
    = label_tag 'generate_thumbnails', 'Generate thumbnails'

%ul{ :class => 'upload_list thumbs_list' }
  %li.add_photos_button
    .image
      = image_tag('add-photos-button.png', :alt => '')
    .title
      Add photos